// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWj2AKB_YoDPf0-qtB0iNlDgx1JMugak',
    appId: '1:584125581314:web:0ad86cdf70c0feb2387f1b',
    messagingSenderId: '584125581314',
    projectId: 'kadoshi-d30a3',
    authDomain: 'kadoshi-d30a3.firebaseapp.com',
    storageBucket: 'kadoshi-d30a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYBPNbr0UsPqzLrju0U8phtQorZnye6I',
    appId: '1:584125581314:android:6a61592229c63419387f1b',
    messagingSenderId: '584125581314',
    projectId: 'kadoshi-d30a3',
    storageBucket: 'kadoshi-d30a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rC6L1fZhJxX_qqYs_AWLJATKIu9RlQE',
    appId: '1:584125581314:ios:21eaba43a851b088387f1b',
    messagingSenderId: '584125581314',
    projectId: 'kadoshi-d30a3',
    storageBucket: 'kadoshi-d30a3.appspot.com',
    iosBundleId: 'com.example.charityCat03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4rC6L1fZhJxX_qqYs_AWLJATKIu9RlQE',
    appId: '1:584125581314:ios:21eaba43a851b088387f1b',
    messagingSenderId: '584125581314',
    projectId: 'kadoshi-d30a3',
    storageBucket: 'kadoshi-d30a3.appspot.com',
    iosBundleId: 'com.example.charityCat03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkWj2AKB_YoDPf0-qtB0iNlDgx1JMugak',
    appId: '1:584125581314:web:58a506c7f2627142387f1b',
    messagingSenderId: '584125581314',
    projectId: 'kadoshi-d30a3',
    authDomain: 'kadoshi-d30a3.firebaseapp.com',
    storageBucket: 'kadoshi-d30a3.appspot.com',
  );
}
